### ISSUE TITLE
no edge present in graph

### ISSUE THREAD

**Issue by Lattesnow** [noriakis/CBNplot#15]
> bngeneplot(results = pway,
+            exp = vsted,
+            expSample = incSample,
+            pathNum = 13, R = 50, showDir = T,
+            convertSymbol = T,
+            expRow = "ENSEMBL",
+            strThresh = 0.7)
'select()' returned 1:many mapping between keys and columns
'select()' returned 1:1 mapping between keys and columns
no edge present in graph

Could you explain why I am getting this? Thanks

**Comment by Lattesnow** [comment]
Does this "no edge" mean I have nothing on the plot?

**Comment by Lattesnow** [comment]
NVM,
solved by update R studio

**Comment by noriakis** [comment]
Thank you for the feedback. I am glad you have solved the problem.
