### ISSUE TITLE
SYMBOL issues

### ISSUE THREAD

**Issue by Farewellznm** [noriakis/CBNplot#19]
When using bngeneplot，if my gene expression data  rownames type is SYMBOL,how to assign the `expRow` Parameters. its seems not works :

bngeneplot(results = pway, exp = vsted, pathNum = 11,expRow = "SYMBOL")

**Comment by noriakis** [comment]
Hi, thanks for reporting the issue. I think the problem can be solved by
specifying `bypassConverting`, default to FALSE.
When specifying, the type of gene description in `enrichResult` and
`expRow` should match.

As SYMBOL is commonly used as an identifier in the expression matrix, I'm
thinking of some ways to automatically infer the type of expRow.

If the problem persists, feel free to paste the code here.
