### ISSUE TITLE
R >= 4.2 is necessary?

### ISSUE THREAD

**Issue by ShixiangWang** [noriakis/CBNplot#2]
Hi @noriakis,

I want to try this tool but find that you limit it with R>=4.2. Is it necessary? As most Linux cannot install with a so new R version due to permission to update the R on a server or other reasons.

Best

Shixiang

**Comment by noriakis** [comment]
Hello @ShixiangWang,
Thank you very much for your comment, and I apologize for the delay in replying.
As you suggested, it is not necessary for the package to work. I put the line for checking the Bioconductor requirements, and I lowered the version requirement now. Once again, I appreciate the important comment.

**Comment by ShixiangWang** [comment]
thank you
